Iter5
BurdinskiiDiu/go-yndx-pr-shortener pull request #33
Opened 2023-05-16 08:44 UTC by BurdinskiiDiu

2023-05-16 22:47 UTC, s-shpak requested changes

2023-05-16 22:47 UTC, s-shpak commented on go.mod
> +module github.com/BurdinskiiDiu/go-yndx-pr-shortener.git
`go.mod` необходимо обновить с помощью `go mod tidy`

2023-05-16 22:47 UTC, s-shpak commented on cmd/config/config.go
> +func ParseFlags(cf *Config) {
Почему бы не создавать объект конфигурации внутри этой функции? Тогда ее можно еще будет переименовать в `GetConfig`

2023-05-16 22:47 UTC, s-shpak commented on cmd/config/config.go
> +		fmt.Println("Need address in a form host:port")
Для логирования лучше использовать `log` (это касается и других вызовов `fmt.Print(ln)` в коде)

2023-05-16 22:47 UTC, s-shpak commented on cmd/config/config.go
> +	da := strings.Split(cf.DefaultAddr, ":")
Я бы лучше перенес эту проверку туда, где это значение используется - кажется, что пакет config не должен знать о бизнес-логике приложения (и, соответственно, валидации аргументов)

2023-05-16 22:47 UTC, s-shpak commented on cmd/store/store.go
> +	sync.Mutex
Не надо встравать мьютекс в структуру, объяви его полем (`mux *sync.Mutex`) и проинициализируй в конструкторе

2023-05-16 22:47 UTC, s-shpak commented on cmd/store/store.go
> +type URLStore interface {
Интерфейс надо объявлять там, где он используется

2023-05-16 22:47 UTC, s-shpak commented on cmd/store/store.go
> +func shorting() string {
Кажется, что `store` не должен заниматься сокращением `URL`

2023-05-16 22:47 UTC, s-shpak commented on cmd/store/store.go
> +	for key, value := range uS.urlStr {
Каждый раз ободить весь словарь - очень дорого. Надо сделать как-то по-другому

2023-05-16 22:47 UTC, s-shpak commented on cmd/store/store.go
> +func (uS *URLStorage) GetLongURL(shrtURL string) (string, error) {
Извлечение значения также надо защищать мьютексом

2023-05-16 22:47 UTC, s-shpak commented on cmd/store/store.go
> +	} else {
Этот `else` не нужен

2023-05-16 22:47 UTC, s-shpak commented on cmd/config/config.go
> +	DefaultAddr string
Лучше переименовать это поле, иначе возникают вопросы

2023-05-16 22:47 UTC, s-shpak commented on internal/app/server/server.go
> +	http.ListenAndServe(sr.conf.DefaultAddr /*":8080"*/, sr.rt)
Этот комментарий не нужен, т.к. адрес будет необязательно `:8080`

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +type Router struct {
deadcode

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +		if r.Method == http.MethodPost {
Сделай обратную проверку, тогда `else` будет не нужен, и твой код станет более плоским

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +			defer r.Body.Close()
Тело  запроса закрывать необязательно

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +				http.Error(w, err.Error(), http.StatusInternalServerError)
Пользователю не надо отправлять причину возникновения внутренней ошибки сервера. А вот залогировать ее стоит

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +				http.Error(w, err.Error(), http.StatusBadRequest)
Это тоже внутренняя ошибка

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +			w.Write([]byte(cf.BaseAddr + "/" + shrtURL))
Ты два раза вычисляешь тело запроса, не повторяйся

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +			srtURL := r.URL.Path
1. Ты используешь роутер, извлекай параметры его средствами
2. Но извлекай их не здесь: если завтра `chi` мы заменим на другой пакет, это сломает эту функцию, что нелогично. Подумай, как это сделать

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler.go
> +			w.Write([]byte("Location: " + lngURL))
Тело ответа не нужно

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler_test.go
> +			//rt := NewRouter(uS)
deadcode

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler_test.go
> +			if i == 0 {
Старайся делать код более плоским, переверни проверку и избавься от `else`

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler_test.go
> +	for i, tc := range testCases {
Я рекоммендую привыкнуть переопределять переменные из цикла внутри этого цикла для тестов (в данном случае `i, tc := i, tc`). Это особенно важно для тестов, т.к. тесты часто запускаются параллельно, а в этом случае возможны проблемы: https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/

2023-05-16 22:47 UTC, s-shpak commented on internal/app/handler/handler_test.go
> +func TestURLShortenerRequest(t *testing.T) {
Обычно разные функции тестируются в разных тестах

2023-05-18 11:17 UTC, BurdinskiiDiu commented on internal/app/handler/handler_test.go
> +			//rt := NewRouter(uS)
Добрый день. Не понял данный момент.

2023-05-18 11:20 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			srtURL := r.URL.Path
Не понял, как за один запрос считать методом роутера chi {id} из path и пропихнуть его дальше в handler, при этом не ломая исходную функцию.

2023-05-18 11:23 UTC, BurdinskiiDiu commented on internal/app/handler/handler_test.go
> +func TestURLShortenerRequest(t *testing.T) {
Правильно ли я понял, что правильно написать две отдельные функции func(t *testing.T)? Тогда мне прийдется определять набор данных для тестов снаружи этих функций, чтобы я мог прокинуть  результат выполнения одной функции в другую?

2023-05-18 11:23 UTC, BurdinskiiDiu commented on internal/app/handler/handler_test.go
> +			if i == 0 {
+

2023-05-18 11:23 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			w.Write([]byte("Location: " + lngURL))
Понял

2023-05-18 11:23 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			w.Write([]byte(cf.BaseAddr + "/" + shrtURL))
Понял

2023-05-18 11:23 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +				http.Error(w, err.Error(), http.StatusBadRequest)
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +				http.Error(w, err.Error(), http.StatusInternalServerError)
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			defer r.Body.Close()
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		if r.Method == http.MethodPost {
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +type Router struct {
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on internal/app/server/server.go
> +	http.ListenAndServe(sr.conf.DefaultAddr /*":8080"*/, sr.rt)
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on cmd/config/config.go
> +	DefaultAddr string
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +	} else {
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +func (uS *URLStorage) GetLongURL(shrtURL string) (string, error) {
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +	for key, value := range uS.urlStr {
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +func shorting() string {
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +type URLStore interface {
Понял

2023-05-18 11:24 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +	sync.Mutex
Понял

2023-05-18 11:25 UTC, BurdinskiiDiu commented on cmd/config/config.go
> +	da := strings.Split(cf.DefaultAddr, ":")
Понял

2023-05-18 11:25 UTC, BurdinskiiDiu commented on cmd/config/config.go
> +		fmt.Println("Need address in a form host:port")
Понял

2023-05-18 11:25 UTC, BurdinskiiDiu commented on cmd/config/config.go
> +func ParseFlags(cf *Config) {
Понял

2023-05-18 11:25 UTC, BurdinskiiDiu commented on go.mod
> +module github.com/BurdinskiiDiu/go-yndx-pr-shortener.git
Понял

2023-05-18 12:38 UTC, BurdinskiiDiu commented on internal/app/handler/handler_test.go
> +	for i, tc := range testCases {
понял

2023-05-18 18:03 UTC, closed without merging

2023-05-18 18:37 UTC, BurdinskiiDiu commented on cmd/config/config.go
> +func ParseFlags(cf *Config) {
+

2023-05-18 18:48 UTC, BurdinskiiDiu commented on cmd/config/config.go
> +	da := strings.Split(cf.DefaultAddr, ":")
+

2023-05-18 18:53 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +	sync.Mutex
+

2023-05-18 18:55 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			w.Write([]byte("Location: " + lngURL))
+

2023-05-18 19:11 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +type URLStore interface {
+

2023-05-18 19:24 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +func shorting() string {
+

2023-05-18 19:25 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +	for key, value := range uS.urlStr {
+

2023-05-18 19:25 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +func (uS *URLStorage) GetLongURL(shrtURL string) (string, error) {
+

2023-05-18 19:26 UTC, BurdinskiiDiu commented on cmd/store/store.go
> +	} else {
+

2023-05-18 19:26 UTC, BurdinskiiDiu commented on cmd/config/config.go
> +	DefaultAddr string
+

2023-05-18 19:26 UTC, BurdinskiiDiu commented on internal/app/server/server.go
> +	http.ListenAndServe(sr.conf.DefaultAddr /*":8080"*/, sr.rt)
+

2023-05-18 19:39 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +				http.Error(w, err.Error(), http.StatusInternalServerError)
+

2023-05-18 19:39 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			defer r.Body.Close()
на это ругается автотест

2023-05-18 19:39 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		if r.Method == http.MethodPost {
+

2023-05-18 19:46 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			w.Write([]byte(cf.BaseAddr + "/" + shrtURL))
+

2023-05-18 19:53 UTC, BurdinskiiDiu commented on internal/app/handler/handler_test.go
> +	for i, tc := range testCases {
+

2023-05-18 19:56 UTC, BurdinskiiDiu commented on internal/app/handler/handler_test.go
> +			if i == 0 {
+