Iter13
BurdinskiiDiu/go-yndx-pr-shortener pull request #69
Opened 2023-06-14 18:30 UTC by BurdinskiiDiu

2023-06-16 14:34 UTC, s-shpak requested changes

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +//db handler
Комментарии к объектам в Go не приянто отделять пустой строкой от комментируемого объекта

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +		err = wS.US.PostShortURL(urlDataStr.ShrtURL, urlDataStr.LngURL, int32(uuid))
1. Если используется Postgres, то не надо посылать запрос для каждого запроса, надо отправить все запросы разом.
2. Я не уерен, что из файла вообще надо переносить данные в БД: этого нет в ТЗ, в реальной жизни я бы исходил из того, что используется либо файловая система, либо БД, а миграции между ними (при необходимости) делаются извне кода

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +	if err := wS.FileFilling(shrtURL, longURL); err != nil {
Получается, что каждый раз, когда мы добавляем что-то в стор, мы автоматически пишем это в файл? Если это так, то это не соответствует ТЗ

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +		urlReq := make([]batchReqStruct, cnt)
Так делать не стоит: `json.Unmarshal` все равно перепишет объект

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +		fmt.Println(urlReq)
deadcode

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +			shortURL, err := wS.CreateShortURL(v.OrigURL)
Если мы имплементируем запись батчем, то не стоит отправлять каждый запрос к БД отдельно

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +				/*wS.logger.Error("PostBatch handler, creating short url err", zap.Error(err))
deadcode

2023-06-16 14:34 UTC, s-shpak commented on internal/app/handler/handler.go
> +				if strings.Contains(err.Error(), "duplicate key value violates") {
Лучше использовать для этой проверки либо `pgerr`, либо `errors.Is`

2023-06-16 14:34 UTC, s-shpak commented on internal/store/store.go
> +func NewURLStorageTest(us *map[string]string, logger *zap.Logger) *URLStorage {
Не увидел в предыдущем ревью: решение не должно содержать код, который используется только тестами. Можно положить эту имплементацию в отдельный пакет, но лучше было бы замокать

2023-06-16 14:34 UTC, s-shpak commented on internal/config/config.go
> +	flag.StringVar(&cf.FileStorePath, "f" /*"/tmp/*/, "short-url-db.json", "full file name for storing url info")
deadcode

2023-06-16 14:34 UTC, s-shpak commented on internal/config/config.go
> +	flag.StringVar(&cf.DBdsn, "d" /*"***postgres:5432/praktikum?sslmode=disable",*/, query, "dsn for db connection")
deadcode

2023-06-16 14:34 UTC, s-shpak commented on internal/config/config.go
> +	StoreType     int
Для этого лучше использовать `enum` (хоть в Go нет этой фичи из коробки): https://stackoverflow.com/questions/14426366/what-is-an-idiomatic-way-of-representing-enums-in-go

Посмотри по ссылке, как используется `iota` с новы типом данных

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +type ClientDB interface {
Этот интерфейс нигде не используется

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +// ///!!!!!!!!!!!!!!!!!!убрать create, усли это не нужно из конфига
Это TODO?

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +	if cDBS.cf.StoreType == 0 {
Кажется, что проверка на тип должна происходить раньше, чтобы мы не заходили в этот метод, если тип стора не БД

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +	cDBS.logger.Info("table is successfuly created")
Весь этот логгинг лучше либо удалить, либо поместить на уровень `Debug`

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +	/*ctx2, cansel2 := context.WithTimeout(cDBS.ctx, 100*time.Second)
deadcode

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +	cDBS.db.Close()
Ошибку надо проверять

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +	ctx, canselFunc := context.WithTimeout(cDBS.ctx, 30*time.Second)
```suggestion
	ctx, cancelCtx := context.WithTimeout(cDBS.ctx, 30*time.Second)
```

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +func (cDBS *ClientDBStruct) Ping() error {
Лучше, если контекст будет передавать извне. Добавить таймаут можно к нему

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +		return err
Ошибку лучше обернуть

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +		cDBS.logger.Error("db ping error")
Зачем логировать ошибку здесь, если она отправляется на уровень выше

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +		ctx2, canselFunc2 := context.WithTimeout(cDBS.ctx, 1*time.Minute)
Не вижу смысла использовать два контекста здесь: такой уровень гранулированности не требуется

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +			cDBS.logger.Info("gotted checkURL is" + checkURL)
Два логгирования не нужно делать

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +		_, err := cDBS.db.ExecContext(ctx2, `INSERT INTO urlstorage(id, short_url, long_url) VALUES ($1, $2, $3)`, uuid, shortURL, longURL)
Если ты делаешь два запроса к БД, то их нужно оборачивать в транзакцию. Но на самом деле можно сделать все за один запрос, посмотри на `ON CONFLICT`

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +				cDBS.logger.Info("catch this error!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
Это стоит переписать

2023-06-16 14:34 UTC, s-shpak commented on internal/postgresql/postgresql.go
> +	if err != nil {
Что произойдет, если в БД нет этой записи? Как мы сможем отличить эту ситуацию от ошибки отправления запроса?

2023-06-19 19:54 UTC, BurdinskiiDiu commented on cmd/shortener/main.go
> +		defer dbStore.Close()
+

2023-06-19 19:55 UTC, BurdinskiiDiu commented on cmd/shortener/main.go
> +		if err != nil {
готово

2023-06-19 19:57 UTC, BurdinskiiDiu commented on cmd/shortener/main.go
> +		logger.Fatal(err.Error())
А получится сделать в данном случае, если мы как раз обрабатываем ошибку при создании самого логгера? Я просто не знаю, корректно это или нет?

2023-06-19 19:58 UTC, BurdinskiiDiu commented on cmd/shortener/main.go
> +		logger.Fatal(err.Error())
Я и подумал, что ее мы можем в случае чего залогировать стандартным логгером, а далее уже везде использовать zap.

2023-06-19 20:02 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +	PostShortURL(string, string, int32) error
готово

2023-06-19 20:03 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +func NewWorkStruct(uS URLStore, cf *config.Config, logger *zap.Logger, ctx context.Context) *WorkStruct {
готово

2023-06-19 20:15 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		ctx:    ctx,
готово

2023-06-19 20:25 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
>  func (wS *WorkStruct) PostLongURL() http.HandlerFunc {
готово

2023-06-19 20:29 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		wS.logger.Info("start post request")
готово

2023-06-19 20:29 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +//db handler
готово

2023-06-19 20:32 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +	if err := wS.FileFilling(shrtURL, longURL); err != nil {
По заданию было  необходимо добавлять все сокращенные url в файл.

2023-06-19 20:35 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +type ClientDB interface {
готово

2023-06-19 20:37 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +// ///!!!!!!!!!!!!!!!!!!убрать create, усли это не нужно из конфига
готово

2023-06-19 20:37 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +	if cDBS.cf.StoreType == 0 {
готово

2023-06-22 13:49 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		shrtURL, err = wS.CreateShortURL(longURL)
готово

2023-06-23 10:56 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +				cDBS.logger.Info("catch this error!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
готово

2023-06-23 14:28 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +		ctx2, canselFunc2 := context.WithTimeout(cDBS.ctx, 1*time.Minute)
готово

2023-06-23 14:29 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +			cDBS.logger.Info("gotted checkURL is" + checkURL)
готово

2023-06-23 14:30 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +		_, err := cDBS.db.ExecContext(ctx2, `INSERT INTO urlstorage(id, short_url, long_url) VALUES ($1, $2, $3)`, uuid, shortURL, longURL)
готово

2023-06-23 17:59 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			if strings.Contains(err.Error(), "duplicate key value violates") {
готово

2023-06-23 18:00 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		err = wS.US.PostShortURL(urlDataStr.ShrtURL, urlDataStr.LngURL, int32(uuid))
готово

2023-06-23 18:16 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		urlReq := make([]batchReqStruct, cnt)
готово

2023-06-23 18:17 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +		fmt.Println(urlReq)
готово

2023-06-23 18:17 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +			shortURL, err := wS.CreateShortURL(v.OrigURL)
готово

2023-06-23 18:17 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +				/*wS.logger.Error("PostBatch handler, creating short url err", zap.Error(err))
готово

2023-06-23 18:18 UTC, BurdinskiiDiu commented on internal/app/handler/handler.go
> +				if strings.Contains(err.Error(), "duplicate key value violates") {
готово

2023-06-23 18:32 UTC, BurdinskiiDiu commented on internal/config/config.go
> +	flag.StringVar(&cf.FileStorePath, "f" /*"/tmp/*/, "short-url-db.json", "full file name for storing url info")
готово

2023-06-23 18:33 UTC, BurdinskiiDiu commented on internal/config/config.go
> +	flag.StringVar(&cf.DBdsn, "d" /*"***postgres:5432/praktikum?sslmode=disable",*/, query, "dsn for db connection")
могу оставить, для тестирования базы локально? чтобы не переписывать каждый раз connectionString?

2023-06-23 18:51 UTC, BurdinskiiDiu commented on internal/config/config.go
> +	StoreType     int
готово

2023-06-23 18:57 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +	cDBS.logger.Info("table is successfuly created")
готово

2023-06-23 18:57 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +	/*ctx2, cansel2 := context.WithTimeout(cDBS.ctx, 100*time.Second)
готово

2023-06-23 18:59 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +	cDBS.db.Close()
готово

2023-06-23 19:10 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +func (cDBS *ClientDBStruct) Ping() error {
готово

2023-06-23 19:19 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +		return err
готово

2023-06-23 19:21 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +		cDBS.logger.Error("db ping error")
готово

2023-06-23 19:21 UTC, BurdinskiiDiu commented on internal/postgresql/postgresql.go
> +	if err != nil {
готово

2023-06-23 20:05 UTC, s-shpak commented on cmd/shortener/main.go
> +		logger.Fatal(err.Error())
все верно

2023-06-23 20:07 UTC, s-shpak approved these changes

2023-06-25 12:27 UTC, merged